//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirCodes.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AirCodes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 IATA,ICAO,Airline,Callsign,Country
        ///M3,TUS,ABSA Cargo Airline,ABSA Cargo,Brazil
        ///GB,ABX,ABX Air,ABEX,USA
        ///9T,RUN,ACT Airlines,CARGO TURK,Turkey
        ///9N,AJV,ANA &amp; JP Express,AYJAY CARGO,Japan
        ///V8,VAS,ATRAN Cargo Airlines,ATRAN,Russia
        ///2E,PHW,AVE.com,PHOENIX SHARJAH,United Arab Emirates
        ///K5,ABE,Aban Air,ABAN,Iran
        ///W9,AAB,Abelag Aviation,ABG,Belgium
        ///MO,AUH,Abu Dhabi Amiri Flight,SULTAN,United Arab Emirates
        ///ZY,ADE,Ada Air,ADA AIR,Albania
        ///JP,ADR,Adria Airways,ADRIA,Slovenia
        ///A3,AEE,Aegean Airlines,AEGEAN,Greece
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string airlines {
            get {
                return ResourceManager.GetString("airlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IATA,ICAO,Location,Airport,Country
        ///BIM,OABN,Bamyan,Bamyan,Afghanistan
        ///BST,OABT,Bost,Bost,Afghanistan
        ///BPM,OAIX,Charikar,Bagram Air Base,Afghanistan
        ///CCN,OACC,Charkhcharan,Charkhcharan,Afghanistan
        ///FBD,OAFZ,Faizabad,Faizabad,Afghanistan
        ///FAH,OAFR,Farah,Farah,Afghanistan
        ///GRG,OAGZ,Gardez,Gardez,Afghanistan
        ///HEA,OAHR,Herat,Herat,Afghanistan
        ///JAA,OAJL,Jalalabad,Jalalabad,Afghanistan
        ///KBL,OAKB,Kabul,Kabul Intl,Afghanistan
        ///KDH,OAKN,Kandahar,Kandahar Intl,Afghanistan
        ///KHT,OAKS,Khost,Khost,Afghanistan
        ///KWH,OAHN, [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string airports {
            get {
                return ResourceManager.GetString("airports", resourceCulture);
            }
        }
    }
}
